# 数据配置
data:
  train_path: "data/dh_msra.txt"
  test_size: 0.2
  val_size: 0.1
  max_seq_length: 128
  label_schema: "BIO"  # BIO或BIOES

# 模型配置
model:
  name: "BiLSTM-CRF"
  embedding_dim: 256
  hidden_dim: 128
  dropout: 0.5
  vocab_size: 5000  # 根据实际词汇表大小调整

# 训练配置
training:
  batch_size: 32
  epochs: 10
  learning_rate: 0.001
  patience: 3  # 早停耐心值
  save_dir: "models/"