default:
    pattern: "*.csv"

datasets:
    hotel_reviews:
        files: "ChnSentiCorp_htl_all.csv"
        encoding: "utf-8"
        columns:
            text: "review"
            label: "label"
    product_reviews:
        pattern: "product_*.csv"